/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-30 07:55:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668943451360L));
    _jspx_dependants.put("jar:file:/D:/MiniProject_SAGAJI/workspace_sagaji/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShoppingMall/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>SAGAJI KOREA | 사가지 코리아</title>\r\n");
      out.write("  <style>\r\n");
      out.write("    /* 공통 */\r\n");
      out.write("    /* 구글 웹 폰트 사용 - Noto Sans Korean */\r\n");
      out.write("    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap');\r\n");
      out.write("\r\n");
      out.write("    html, body {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      position: relative;\r\n");
      out.write("\r\n");
      out.write("      /* 구글 웹 폰트 사용 - Noto Sans Korean */\r\n");
      out.write("      font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #top {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 38px;\r\n");
      out.write("      margin: 0px;\r\n");
      out.write("      padding: 0px;\r\n");
      out.write("      background-color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #header-container {\r\n");
      out.write("      margin: 0 auto;\r\n");
      out.write("      padding: 10px 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header {\r\n");
      out.write("      display: flex; \r\n");
      out.write("      margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header a {\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("		  color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menuImg-wrapper {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      width: 40px;\r\n");
      out.write("      height: 40px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menuImg-wrapper:hover {\r\n");
      out.write("      background-color: #f3f1f1;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menu {\r\n");
      out.write("      margin-top: -2px;\r\n");
      out.write("      margin-left: 8px;\r\n");
      out.write("      font-size: 0.9rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #main-header-search {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #main-header-search a {\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("		  color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 로고 영역*/\r\n");
      out.write("    #main-header-search #logo-wrapper {\r\n");
      out.write("      margin-left: 60px;\r\n");
      out.write("      margin-right: 40px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 돋보기 아이콘 및 검색어 입력 영역*/\r\n");
      out.write("    #main-header-search #search-wrapper {\r\n");
      out.write("      width: 1000px;\r\n");
      out.write("      height: 55px;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      padding-left: 15px;\r\n");
      out.write("      background-color: #f3f1f1;\r\n");
      out.write("      border-radius: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #main-header-search #search-wrapper:hover {\r\n");
      out.write("      background-color: #DFDFDF;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #search-wrapper #searchKeyword {\r\n");
      out.write("      width: 920px;\r\n");
      out.write("      height: 30px;\r\n");
      out.write("      margin: 10px;\r\n");
      out.write("      border:none;\r\n");
      out.write("      background-color: #f3f1f1;\r\n");
      out.write("      background: transparent;\r\n");
      out.write("      /* input 테그 클릭 시, 기본적으로 생기는 테두리 제거 */\r\n");
      out.write("      outline: none;\r\n");
      out.write("      /* input 태그 자동완성 선택 시, 배경색 변경되는 부분 막기 */\r\n");
      out.write("      \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #main-header-login {\r\n");
      out.write("      width: 200px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      margin-left: 60px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #main-header-login #personImg {\r\n");
      out.write("      margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #main-header-login:hover {\r\n");
      out.write("      background-color: #f3f1f1;\r\n");
      out.write("      border-radius: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* SAGAJI 로고 크기 */\r\n");
      out.write("    .logoImg {\r\n");
      out.write("      width: 90px;\r\n");
      out.write("      height: 36px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 메뉴, 돋보기, 사람모양 아이콘 크기 */\r\n");
      out.write("    #menuImg, #searchImg, #personImg {\r\n");
      out.write("      width: 24px;\r\n");
      out.write("      height: 24px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul, li {\r\n");
      out.write("		  list-style: none;\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("    .listField, .main-nav-field, .detail-nav-field {\r\n");
      out.write("      margin-left: 0;\r\n");
      out.write("      padding-left: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav #nav-wrapper {\r\n");
      out.write("      margin-left: 90px;\r\n");
      out.write("      margin-right: 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a {\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("		  color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav #main-nav {\r\n");
      out.write("      float: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* \r\n");
      out.write("      모든 제품, 신제품, SAGAJI 인기제품 배치\r\n");
      out.write("      문의사항, 주문조회, 내 정보 배치\r\n");
      out.write("    */\r\n");
      out.write("    .main-nav-field, .detail-nav-field {\r\n");
      out.write("      display: flex;\r\n");
      out.write("		  justify-content: space-between;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .main-nav-field li {\r\n");
      out.write("      margin-right: 35px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* nav항목들 hover 시, 밑줄 효과 */\r\n");
      out.write("    .main-nav-field li a:hover, .detail-nav-field li a:hover {\r\n");
      out.write("      text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .detail-nav-field li {\r\n");
      out.write("      margin-left: 35px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav #detail-nav {\r\n");
      out.write("      float: right;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav hr {\r\n");
      out.write("      clear: both;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 로그인 영역, nav항목들 글씨 설정 */\r\n");
      out.write("    #main-header-login, .main-nav-field, .detail-nav-field {\r\n");
      out.write("      font-size: 0.9rem;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 메뉴 클릭 시, 나타나는 메뉴 리스트 영역 */\r\n");
      out.write("    #menuList {\r\n");
      out.write("      width: 480px;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      padding-top: 30px;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      display: none;\r\n");
      out.write("      /* \r\n");
      out.write("        화면 겹침 순서\r\n");
      out.write("        -> 혹시 모르기에 큰 값으로 설정해둠.\r\n");
      out.write("        -> 가장 맨 앞의 화면\r\n");
      out.write("      */\r\n");
      out.write("      z-index: 9999; \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* X 아이콘 크기 */\r\n");
      out.write("    #xImg {\r\n");
      out.write("      width: 20px;\r\n");
      out.write("      height: 20px;\r\n");
      out.write("    } \r\n");
      out.write("\r\n");
      out.write("    #imgWrapper {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #xImg-wrapper {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      width: 40px;\r\n");
      out.write("      height: 40px;\r\n");
      out.write("      margin-left: 60px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #imgWrapper #xImg-wrapper:hover {\r\n");
      out.write("      background-color: #f3f1f1;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #imgWrapper .logoImg {\r\n");
      out.write("      margin-left: 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #listWrapper {\r\n");
      out.write("      float: left;\r\n");
      out.write("      margin-top: 40px;\r\n");
      out.write("      margin-left: 150px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .listField {\r\n");
      out.write("      margin-left: 0;\r\n");
      out.write("      padding-left: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .listField a {\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .listField li {\r\n");
      out.write("      margin-bottom: 10px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .listField li:nth-child(1) {\r\n");
      out.write("      font-size: 2.2rem;\r\n");
      out.write("      margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .listField li:hover {\r\n");
      out.write("      text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 메뉴 아이콘 클릭 시, 배경 투명하게 설정 */\r\n");
      out.write("    #transparent-background {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      background-color: #C0C0C0;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      opacity: 0.5;\r\n");
      out.write("      display: none;\r\n");
      out.write("      /* \r\n");
      out.write("        화면 겹침 순서\r\n");
      out.write("        -> 혹시 모르기에 큰 값으로 설정해둠. \r\n");
      out.write("      */\r\n");
      out.write("      z-index: 8888; \r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div id=\"transparent-background\"></div>\r\n");
      out.write("  <div id=\"menuList\">\r\n");
      out.write("    <div id=\"imgWrapper\">\r\n");
      out.write("      <div id=\"xImg-wrapper\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/x.png\" id=\"xImg\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/logo.png\" class=\"logoImg\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"listWrapper\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("      <ul class=\"listField\">\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"top\"></div>\r\n");
      out.write("  <div id=\"header-container\">\r\n");
      out.write("    <header>\r\n");
      out.write("        <div id=\"main-header-menu\">\r\n");
      out.write("          <div id=\"menuImg-wrapper\">\r\n");
      out.write("            <a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/menu.png\" id=\"menuImg\"></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"menu\">\r\n");
      out.write("            <a href=\"#\">메뉴</a>\r\n");
      out.write("          </div> \r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"main-header-search\">\r\n");
      out.write("          <div id=\"logo-wrapper\">\r\n");
      out.write("            <a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/logo.png\" class=\"logoImg\"></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div id=\"search-wrapper\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/search.png\" id=\"searchImg\">\r\n");
      out.write("            <input type=\"text\" name=\"searchKeyword\" id=\"searchKeyword\" placeholder=\"검색어 입력\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"main-header-login\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/person.png\" id=\"personImg\">\r\n");
      out.write("          <a href=\"/user/login.do\">로그인 또는 가입하기</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <nav>\r\n");
      out.write("      <div id=\"nav-wrapper\">\r\n");
      out.write("        <div id=\"main-nav\">\r\n");
      out.write("          <ul class=\"main-nav-field\">\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\">모든 제품</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\">신제품</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\">SAGAJI 인기제품</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"detail-nav\">\r\n");
      out.write("          <ul class=\"detail-nav-field\">\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\">문의사항</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\">주문조회</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#\">내 정보</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr/>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script>\r\n");
      out.write("    $(function() {\r\n");
      out.write("		// 메뉴 아이콘 클릭 시\r\n");
      out.write("		$(\"#menuImg\").on(\"click\", function() {\r\n");
      out.write("		  $(\"#transparent-background\").css(\"display\", \"block\");\r\n");
      out.write("		  $(\"#menuList\").css(\"display\", \"block\");\r\n");
      out.write("		  $(\"#menuList\").css(\"overflow\", \"scroll\");\r\n");
      out.write("		  $(\"html\").css(\"overflow\", \"hidden\");\r\n");
      out.write("		  /* 메뉴 리스트 이외에 마우스 포인터 먹지 않게 설정 */\r\n");
      out.write("		  $(\"#header-container\").css(\"pointer-events\", \"none\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// X 아이콘 클릭 시\r\n");
      out.write("		$(\"#xImg\").on(\"click\", function() {\r\n");
      out.write("		  $(\"#transparent-background\").css(\"display\", \"none\");\r\n");
      out.write("		  $(\"#menuList\").css(\"display\", \"none\");\r\n");
      out.write("		  $(\"html\").css(\"overflow\", \"auto\");\r\n");
      out.write("		  $(\"#header-container\").css(\"pointer-events\", \"auto\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 메뉴 리스트 영역 이외에 다른 영역 클릭 시, 메인 페이지로 돌아옴\r\n");
      out.write("		$(\"#transparent-background\").on(\"click\", function() {\r\n");
      out.write("		  $(\"#xImg\").trigger(\"click\");\r\n");
      out.write("		});\r\n");
      out.write("      \r\n");
      out.write("      	// 카테고리 리스트 조회\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"/product/getCategoryList.do\",\r\n");
      out.write("			type: \"post\",\r\n");
      out.write("			success: function(obj) {\r\n");
      out.write("				console.log(obj);\r\n");
      out.write("				// JSON 형태로 변환하여 키를 통해 값을 꺼냄\r\n");
      out.write("				let data = JSON.parse(obj);\r\n");
      out.write("				\r\n");
      out.write("				let htmlStr = \"\";\r\n");
      out.write("				\r\n");
      out.write("				for(let i=0; i<data.categoryList.length; i++) {\r\n");
      out.write("					htmlStr += \"<li>\";\r\n");
      out.write("					htmlStr += \"<a href='/product/getCategoryProductList.do?categoryCd=\" + data.categoryList[i].categoryCd + \r\n");
      out.write("								\"'>\" + data.categoryList[i].categoryNm + \"</a>\";\r\n");
      out.write("					htmlStr += \"</li>\";\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				// ul에 직접 만들어준 li 생성\r\n");
      out.write("				$(\".listField\").append(htmlStr);\r\n");
      out.write("			},\r\n");
      out.write("			error: function(e) {\r\n");
      out.write("				console.log(e);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("      	\r\n");
      out.write("      	// 헤더의 로고 이미지 클릭 시, main 화면으로 이동\r\n");
      out.write("      	$(\".logoImg\").on(\"click\", function() {\r\n");
      out.write("      		location.href=\"/\";\r\n");
      out.write("      	});\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
