/*
	< 테이블 생성 스크립트 >
*/
-- 1. T_SGJ_USER(회원정보 테이블)
CREATE TABLE T_SGJ_USER (
	USER_ID VARCHAR(30) PRIMARY KEY,
	USER_PW VARCHAR(45) NOT NULL,
	USER_NM VARCHAR(30) NOT NULL,
	USER_TEL VARCHAR(20) NOT NULL,
	USER_EMAIL VARCHAR(30) NOT NULL,
	USER_ADDR1 VARCHAR(200) NOT NULL,
	USER_ADDR2 VARCHAR(200) NOT NULL,
	USER_TYPE VARCHAR(5) NOT NULL DEFAULT 'USER',
	USER_RGST_DATE DATETIME NOT NULL DEFAULT NOW(),
	USER_MODF_DATE DATETIME NOT NULL DEFAULT NOW(),
	USER_USE_YN CHAR(1) NOT NULL DEFAULT 'Y'
);

-- 2. T_SGJ_USER_ADDR(회원주소(배송주소) 테이블)
CREATE TABLE T_SGJ_USER_ADDR (
	USER_ID VARCHAR(30),
	ADDR_NO INT,
	USER_ADDR1 VARCHAR(200) NOT NULL,
	USER_ADDR2 VARCHAR(200) NOT NULL,
	ZIP_CD VARCHAR(5) NOT NULL,
	ADDR_RGST_DATE DATETIME NOT NULL DEFAULT NOW(),
	ADDR_MODF_DATE DATETIME NOT NULL DEFAULT NOW(),
	BASIC_ADDR_YN CHAR(1) NULL DEFAULT 'N',
	USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT PRIMARY KEY(USER_ID, ADDR_NO)
);

-- 3. T_SGJ_PRDCT(제품 테이블)
CREATE TABLE T_SGJ_PRDCT (
	PRDCT_NO VARCHAR(20) PRIMARY KEY,
	PRDCT_NM VARCHAR(50) NOT NULL,
    PRDCT_INFO VARCHAR(300) NOT NULL,
	PRDCT_RGST_DATE DATETIME NOT NULL DEFAULT NOW(),
	PRDCT_USE_YN CHAR(1) NOT NULL DEFAULT 'Y'
);

-- 4. T_SGJ_PRDCT_DETAIL(제품_상세 테이블)
CREATE TABLE T_SGJ_PRDCT_DETAIL (
	PRDCT_NO VARCHAR(20),
	PRDCT_DETAIL_NO INT,
	PRDCT_CATEGORY_CD INT NOT NULL,
	PRDCT_SIZE VARCHAR(50) NOT NULL,
	PRDCT_COLOR VARCHAR(5) NOT NULL,
	PRDCT_MATERIAL VARCHAR(5) NOT NULL,
	PRDCT_PRICE INT NOT NULL,
	PRDCT_REMAIN INT NOT NULL,
	PRDCT_DETAIL_RGST_DATE DATETIME NOT NULL DEFAULT NOW(),
	PRDCT_MODF_DATE DATETIME NOT NULL DEFAULT NOW(),
	PRDCT_DETAIL_USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT PRIMARY KEY(PRDCT_NO, PRDCT_DETAIL_NO)
);

-- 5. T_SGJ_ORDER(주문 테이블)
CREATE TABLE T_SGJ_ORDER (
	ORDER_NO INT PRIMARY KEY AUTO_INCREMENT,
	USER_ID VARCHAR(30) NOT NULL,
	ORDER_DATE DATETIME NOT NULL DEFAULT NOW(),
	ORDER_TOTAL_AMT INT NOT NULL DEFAULT 0,
	PAY_YN CHAR(1) NOT NULL DEFAULT 'N',
	CANCEL_YN CHAR(1) NULL DEFAULT 'N'
);

-- 6. T_SGJ_ORDER_ITEM(주문_상세 테이블)
CREATE TABLE T_SGJ_ORDER_ITEM (
	ORDER_NO INT,
	PRDCT_NO VARCHAR(20),
	PRDCT_DETAIL_NO INT,
	ORDER_CNT INT NOT NULL,
	ORDER_AMT INT NOT NULL,
    CONSTRAINT PRIMARY KEY(ORDER_NO, PRDCT_NO, PRDCT_DETAIL_NO)
);

-- 7. T_SGJ_CART(장바구니 테이블)
CREATE TABLE T_SGJ_CART (
	USER_ID VARCHAR(30),
	PRDCT_NO VARCHAR(20),
    PRDCT_DETAIL_NO INT,
	CART_CNT INT NOT NULL,
	CART_RGST_DATE DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT PRIMARY KEY(USER_ID, PRDCT_NO, PRDCT_DETAIL_NO)
);

-- 8. T_SGJ_WISHITEM(찜 상품 테이블)
CREATE TABLE T_SGJ_WISHITEM (
	USER_ID VARCHAR(30),
	PRDCT_NO VARCHAR(20),
    PRDCT_DETAIL_NO INT,
	WISH_RGST_DATE DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT PRIMARY KEY(USER_ID, PRDCT_NO, PRDCT_DETAIL_NO)
);

-- 9. T_SGJ_QUESTION(문의사항 테이블)
CREATE TABLE T_SGJ_QUESTION (
	QUESTION_NO INT PRIMARY KEY,
	QUESTION_TITLE VARCHAR(150) NOT NULL,
	QUESTION_CONTENT VARCHAR(1500) NOT NULL,
	QUESTION_RGST_DATE DATETIME NOT NULL DEFAULT NOW(),
	QUESTION_STATE VARCHAR(20) NOT NULL DEFAULT '접수중',
	QUESTION_ANSWER VARCHAR(1500) NULL,
	USER_ID VARCHAR(30) NOT NULL,
	QUESTION_SECRET_YN CHAR(1) NULL DEFAULT 'N'
);

-- 10. T_SGJ_CATEGORY(제품_카테고리 테이블)
CREATE TABLE T_SGJ_CATEGORY (
	CATEGORY_CD INT PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_NM VARCHAR(30) NOT NULL,
	CATEGORY_USE_YN CHAR(1) NOT NULL DEFAULT 'Y'
);

-- 11. T_SGJ_IMAGE(제품_이미지 테이블)
CREATE TABLE T_SGJ_IMAGE (
	PRDCT_NO VARCHAR(20),
	PRDCT_DETAIL_NO INT,
	PRDCT_IMAGE_NO INT,
	PRDCT_IMAGE_NM VARCHAR(100) NOT NULL,
	PRDCT_IMAGE_TYPE VARCHAR(10) NOT NULL,
    CONSTRAINT PRIMARY KEY(PRDCT_NO, PRDCT_DETAIL_NO, PRDCT_IMAGE_NO)
);

-- 12. T_SGJ_CMMN_CD(공통코드 테이블)
CREATE TABLE T_SGJ_CMMN_CD (
	CD VARCHAR(5) PRIMARY KEY,
	HIGH_CD VARCHAR(5) NULL,
	CD_NM VARCHAR(45) NULL
);