/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-30 08:24:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>로그인 - SAGAJI</title>\r\n");
      out.write("<style>\r\n");
      out.write("    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=swap');\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ========== 영역 ========== */\r\n");
      out.write("    .form-wrapper {\r\n");
      out.write("        line-height: 1.5;\r\n");
      out.write("        scroll-behavior: smooth;\r\n");
      out.write("        box-sizing: inherit;\r\n");
      out.write("        outline: none;\r\n");
      out.write("    }\r\n");
      out.write("    /* 왼쪽사이드 */\r\n");
      out.write("    .section1 { \r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        float: left;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        padding: 0 80px;\r\n");
      out.write("        background-color: #0058A3;\r\n");
      out.write("        scroll-behavior: smooth;\r\n");
      out.write("    }\r\n");
      out.write("    /* 오른쪽사이드 */\r\n");
      out.write("    .section2 {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        /* flex-direction: column; */\r\n");
      out.write("        /* justify-content: space-between; */\r\n");
      out.write("        float: right; \r\n");
      out.write("        width: calc(100% - 620px);\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        padding: 0 80px;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        scroll-behavior: smooth;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    /* ========== section1 - 왼쪽사이드 ========== */\r\n");
      out.write("    a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    .back {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        font-size: 2em;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("    }\r\n");
      out.write("    .logo {\r\n");
      out.write("        display: inline-flex;\r\n");
      out.write("        padding: 0 0 0 54px;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 1.2em;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .title{\r\n");
      out.write("        color: yellow;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .copyright {\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ========== section2 - 오른쪽사이드 ========== */\r\n");
      out.write("    .content {\r\n");
      out.write("        width: 700px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    .label_wrapper1 {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .label_wrapper2 {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* input-text */\r\n");
      out.write("    .input_wrapper {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .input input {\r\n");
      out.write("        flex-grow: 1;\r\n");
      out.write("        border: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        padding-inline-start: 0.5rem;\r\n");
      out.write("        padding-inline-end: 0.5rem;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        line-height: 1.5;\r\n");
      out.write("        height: 3rem;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        order: 3;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        outline: none;\r\n");
      out.write("    }\r\n");
      out.write("    .input_border {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        bottom: 0;\r\n");
      out.write("        display: block;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        border: 1px solid #929292;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        pointer-events: none;\r\n");
      out.write("    }\r\n");
      out.write("    /* border_error  ->  border: 1px solid #e00751; */\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    /* 버튼 */\r\n");
      out.write("    .btn2 {\r\n");
      out.write("        width:100%;\r\n");
      out.write("        margin-top: 50px;\r\n");
      out.write("        min-height: 4rem;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 64px;\r\n");
      out.write("        background: #0058A3;;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 1.5em;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn_inner {\r\n");
      out.write("        border-radius: 64px;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"form-wrapper\">\r\n");
      out.write("        <!-- ★action 수정하기 -->\r\n");
      out.write("        <form id=\"loginForm\" action=\"/user/login.do\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" id=\"loginMsg\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("            <!-- ========== 왼쪽사이드 ========== -->\r\n");
      out.write("            <div class=\"section1\">\r\n");
      out.write("                <!-- 메인페이지 버튼, 로고 (★href 메인페이지로 입력) -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <a href=\"javascript:history.back();\" class=\"back\">←</a>\r\n");
      out.write("                    <a href=\"/\"; class=\"logo\"><h1>SAGAJI</h1></a>\r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <!-- 타이틀: 로그인 -->\r\n");
      out.write("                <div class=\"title\">\r\n");
      out.write("                    <h1>로그인</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <!-- copyright 내용 -->\r\n");
      out.write("                <div class=\"copyright\">\r\n");
      out.write("                    <p>ⓒ Inter SAGAJI MALL Systems 2022</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ========== 오른쪽사이드 ========== -->\r\n");
      out.write("            <div class=\"section2\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("    \r\n");
      out.write("                    <!-- userId -->\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"label_wrapper1\"><label for=\"userId\">아이디</label></div>\r\n");
      out.write("                        <div class=\"input  label_wrapper2\">\r\n");
      out.write("                            <div class=\"input_wrapper\">\r\n");
      out.write("                                <input type=\"text\" name=\"userId\" id=\"userId\" required placeholder=\"아이디를 입력하세요.\">\r\n");
      out.write("                                <span class=\"input_border\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                    <!-- userPw1 -->\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"label_wrapper1\"><label for=\"userPw\">비밀번호</label></div>\r\n");
      out.write("                        <div class=\"input  label_wrapper2\">\r\n");
      out.write("                            <div class=\"input_wrapper\">\r\n");
      out.write("                                <input type=\"password\"  name=\"userPw\" id=\"userPw\" required placeholder=\"비밀번호를 입력하세요.\">\r\n");
      out.write("                                <span class=\"input_border\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p id=\"pwValidation\" style=\"color: red; font-size: 0.8rem;\">\r\n");
      out.write("                        비밀번호는 영문자, 숫자, 특수문자 조합의 9자리 이상으로 입력해주세요.\r\n");
      out.write("                    </p>\r\n");
      out.write("    \r\n");
      out.write("                    <!-- login button -->\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <button type=\"button\" class=\"btn2\" id=\"btnLogin\">\r\n");
      out.write("                        <span class=\"btn_inner\">로그인</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- join button -->\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <button type=\"button\" onclick = \"location.href='/user/join.do'\" class=\"btn2\" id=\"btnJoin\" style=\" margin-top: 18px; border: 1px solid #0058A3; background-color: white; color: #0058A3; font-weight: 700;\">\r\n");
      out.write("                        <a href=\"/user/join.do\" style= \"color: #0058A3;\">회원가입</a>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("			//로그인 성공 시 메시지 출력\r\n");
      out.write("			if($(\"#loginMsg\").val() != \"\" && $(\"#loginMsg\").val() != null) {\r\n");
      out.write("				alert($(\"#loginMsg\").val());\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			var pwValidation = false;\r\n");
      out.write("			$(\"#pwValidation\").hide();\r\n");
      out.write("			\r\n");
      out.write("			//로그인 시 아이디나 비밀번호가 틀렸을 경우에\r\n");
      out.write("			//대비하여 폼 서브밋 대신 ajax로 처리\r\n");
      out.write("			$(\"#btnLogin\").on(\"click\", function() {\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"/user/login.do\",\r\n");
      out.write("					type: \"post\",\r\n");
      out.write("					data: $(\"#loginForm\").serialize(),\r\n");
      out.write("					success: function(obj) {\r\n");
      out.write("						console.log(obj);\r\n");
      out.write("						//id 체크\r\n");
      out.write("						if(obj == \"idFail\") {\r\n");
      out.write("							alert(\"존재하지 않는 아이디입니다.\");\r\n");
      out.write("							$(\"#userId\").focus();\r\n");
      out.write("							return;\r\n");
      out.write("						}\r\n");
      out.write("						\r\n");
      out.write("						//pw 체크\r\n");
      out.write("						if(obj ==\"pwFail\") {\r\n");
      out.write("							alert(\"비밀번호가 틀렸습니다. 비밀번호를 확인해주세요.\");\r\n");
      out.write("							$(\"#userPw\").focus();\r\n");
      out.write("							return;\r\n");
      out.write("						}\r\n");
      out.write("						\r\n");
      out.write("						//로그인 처리\r\n");
      out.write("						location.href=\"/\";\r\n");
      out.write("					},\r\n");
      out.write("					error: function(e) {\r\n");
      out.write("						console.log(e);\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("			function validatePassword(character) {\r\n");
      out.write("				return /^(?=.*[a-zA-Z])(?=.*[!@#$%^&*+=-])(?=.*[0-9]).{9,}$/.test(character);\r\n");
      out.write("			}\r\n");
      out.write("			$(\"#userPw\").on(\"change\", function() {\r\n");
      out.write("				//비밀번호 유효성 처리\r\n");
      out.write("				if(!validatePassword($(\"#userPw\").val())) {\r\n");
      out.write("					pwValidation = false;\r\n");
      out.write("					$(\"#pwValidation\").show();\r\n");
      out.write("					$(\"#userPw\").focus();\r\n");
      out.write("				} else {\r\n");
      out.write("					pwValidation = true;\r\n");
      out.write("					$(\"#pwValidation\").hide();\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
